[monitor]
wait=1000 # 1000 seconds / ~16min

[[searches]]
name="shoes"
terms=[
    "gaziano",
    "santoni",
    "lobb",
    "yanko",
    "vass",
    "lattanzi",
    "alden",
    "church",
    "corthay",
    "crispin",
    "edward green",
    "crockett",
    "alfred sargent",
    "alfred sargeant",
    "demeter",
    "heschung",
    "carlos santos",
    "carmina"
]
price_max=150
category='shoes'


[[searches]]
name="shirts"
terms=[
    "suitsupply",
    "eton"
]
price_max=20
category='clothes'

[[searches]]
name="clothes"
terms=[
    "suitsupply",
    "barbour",
    "hackett",
    "hacket"
]
price_max=100
category='clothes'

